spring.application.name=backend-tattoodarte
spring.datasource.url=jdbc:sqlserver://localhost\\MSSQLLocalDB;databaseName=TattooDarte;encrypt=true;trustServerCertificate=true
spring.datasource.username=jdart
spring.datasource.password=T4tt00$
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect